doctrine:
    dbal:
        default_connection: default
        connections:
            default:
#                driver:   pdo_mysql
                #driver_class: Doctrine\DBAL\Driver\PDO\PgSQL\Driver
                driver_class: Doctrine\DBAL\Driver\PDO\PgSQL\Driver
                host:     '%env(resolve:DATABASE_HOST)%' #'%database_host%'
                port:     '%env(resolve:DATABASE_PORT)%' #'%database_port%'
                dbname:   '%env(resolve:DATABASE_NAME)%' #'%database_name%'
                user:     '%env(resolve:DATABASE_USER)%' #'%database_user%'
                password: '%env(resolve:DATABASE_PASSWORD)%' #'%database_password%'
                charset:  UTF8
#
#    orm:
#        default_entity_manager: default
#        auto_generate_proxy_classes: true
#        entity_managers:
#            default:
#                connection: default
#                mappings:
#                    Default:
#                        is_bundle: false
#                        type: annotation
#                        dir: '%kernel.project_dir%/src/Entity'
#                        prefix: 'App\Entity'
#                        alias: Default
