services:
  level.mapper:
    class: App\Model\Level\LevelMapper
    public: true

  userLevel.mapper:
    class: App\Model\UserLevel\UserLevelMapper
    public: true

  question.mapper:
    class: App\Model\Question\QuestionMapper
    public: true

  answer.mapper:
    class: App\Model\Answer\AnswerMapper
    public: true

  directory.mapper:
    class: App\Model\Directory\DirectoryMapper
    public: true