parameters:

  localeCache.defaultLifetime: 30
  localeCache.limitEntityAmount: 100

  logger.host:        'logstash'
  logger.port:        5000
  logger.filePath:    '%kernel.project_dir%/var/log/'
  logger.levelLimit:  'warning'

  clientConnectionTimeout: 10
