services:
  countryRepository:
    class: App\Repository\CountryRepository
    arguments:
      - '@App\doctrine\pgsql\Connection'
      - '@countryMapper'
    public: true

  bookRepository:
    class: App\Repository\BookRepository
    arguments:
      - '@App\doctrine\pgsql\Connection'
      - '@bookMapper'
    public: true